### PR TITLE
FIXES TODO in callbacks: implement strict validation for all payment callbacks

### LINKED ISSUE #461: Implement strict validation for payment callback webhooks
### Description
The payment callback endpoints currently process external webhook data without a centralized validation layer. This introduces potential risks related to malformed payloads, inconsistent structures, and unsafe data handling.

This issue proposes implementing strict request validation for all supported payment processor callbacks.

---

### Proposed Solution
Introduce a unified schema-based validation system for incoming webhook requests.

Key tasks:
- Create centralized schema definitions for callback payloads
- Validate all incoming callback requests before business logic execution
- Align callback validation with the project's existing validation patterns

---

### Additional Context
Related TODO:
`Validate markers in src/controllers/callbacks/`

### PR DESCRIPTION
**Pull request by Mohit-Davar**
## Description
This pull request implements strict request validation for all supported payment processor callbacks (LNbits, Nodeless, OpenNode, and Zebedee).

**Changes include:**
- **Centralised Schema Layer:** Created callback-request-schemas.ts to isolate and manage third-party webhook structures.
- **Joi based verification:** Instead of relying on manual verification for every callback (like manually checking hex patterns or string lengths), I've moved everything to use Joi schemas and bringing the callback logic in line with how the rest of the project handles validation.

## Related Issue
Resolves internal TODO: Validate markers in src/controllers/callbacks/.

## Motivation and Context
The payment callback endpoints were previously processing external data without strict validation. This change ensures that all incoming webhooks from external processors are verified for correct structure and data types before any business logic is executed.

## How Has This Been Tested?
I have implemented a unit test suite in callback-request-schemas.spec.ts

## Screenshots (if appropriate):
Implemented these TODOs:

image

Test Cases:

image

## Types of changes

- [ ] Non-functional change (docs, style, minor refactor)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my code changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by cameri** [comment]
@Mohit-Davar Appreciate your work here. Could you please create the issue for this PR?

File: src/schemas/callback-request-schemas.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import { idSchema, pubkeySchema } from './base-schema'
```
Comment (cameri) [inline src/schemas/callback-request-schemas.ts]: Could you please split this file into one per callback controller?

**Comment by cameri** [comment]
@Mohit-Davar kindly create the associated issue for this PR 🙏

**Comment by Mohit-Davar** [comment]
@cameri Thank you for reviewing my PRs earlier and for the detailed feedback. I’ve addressed all the requested changes and updated the PRs accordingly.
Could you please let me know if anything else is required from my side, or if there are any additional improvements I should make before they can be merged?
I really appreciate your time and guidance. Looking forward to your feedback. 🙂

**Review by cameri — APPROVED** [review]
